language: node_js
node_js: stable
env:
  global:
  #- secure: jDsXwG3NJ87l3QGO8lxL2hUIBmu5EVSMbbf+9ueU4R6u2DlFw+oeDFanOTtdXKzXismrF8dWj/q3Ze8PEfQCfL+X4wVD9yLYS4SMDC02ed54v2UKi9nkYndLEa2ejQe9z/FsSmYYoIWkEaY0FSVHp3DHyg+PS4uqgMQHipv7TI4Bib5QMsVJ8HeqXXmcYA90uUrvrzkhlgWzFpEmdhcq0L7aM9+KSgY3UqrlmujGfGMUzG7cfyw8S1leqmckW/XLd1YscnOQwx0ZNoFf52+2fVBjXnpb+WS0FkqgOpZj7sKWoFEvnbKfhbBOuzzIgFOOHzcZQ9onnUclPJ3qZMQ8NHiFeG62Pu2z51D2oET6z+s+foC4WcZH5WqAPYrWVlen/3XA7ijeokfabFNjBm7Xyb8dJZFh7KgpZge9qDkugB9y/n07rZ8s6WMo+3+lrOiVdIrzVr5sI3qsxjQKlgmpz6obf9L1geRfBaNdfdhCsqujTk6rDSO7HVFBmxGboRyDjCrhawxybNi/FYWsqGuj91XC/VdNDDYgww++CrJwL3pVRtIcxDexkW9lyWZgn9w1ARNpNp0ihqX1XBe3EFQdyqRhO3ITdFI7gjRK/BzYOgEgG+yeFYH7k5OWNFFswtFqMhShD1Ey8lVk37crotlV3xXXUdNUkPpzgWtVhWsrzz8=
  #- secure: n0+b9p0iSqSU6shUrrOCcHJczjEQGR9RSaJTW6eyoVXl2sgC93lbA62b5Vp5BJOPTesQ7M/tl4sF8vXo6NHg6K06v1tBsKn/TgBzU9cr2IeFkV2uK2qmIaGMBK2Vmreqi8bGbnzHiii2lDp+0wlWfmfwj1Xs2CK9gDbVscjuJq4CEDr6127GBzXjXEZrWDwa4qywrhCQJU//dRJiMjBhq89p0Ca9dJQr4IsVoBItEySpd0NWOSaAx9CXVwA+1NbGATuzJ1fPre7CqT39QXeyxjpF62Z07wsdtf5KRQDZMIKertY852A59M605sLmE9HuFQtv6bC0Aq/vCShRTYtTxnE5Mq6qRnn9XyMTIvCVy55uuxk4+UaYHnUz1vre5oeAmyUmrt6f6ewbFhLRDCJHRsQpnYuudPFLpaTB8oXoU+fy1Y1Y8OiDH1iwFpdFRCmoBLLMKB+FepMM1Fw/FLOuzyuVIe8hIUKMyUFGPfBk8PBcgteshhIobj5XWfv6Vf/Q5hVGffZrJ8L9zyM15vT25e93629Kfln+UP/cBfaF3wigjrJJ9VpY92M9xR/9Dxk5exlwEeNC5M9uzKzgU1nodyOAQiG/GZ8j74HPvwJRpMPMSmtjClIx2btHqLhMlPUdGcA+cPTxTga1XRzPkY/hx099mY73rQgKZozV8ulUK8s=
  #- secure: ZrHqr+opTg7LExcqIEQgY8djmta0V/rDj1xJB6RaE3kmpvOdaWyU3Oe1VCiekJmqia1CdiFlg/8eYDL8HPPGCfoq7cQbQMpxFoAIv0zbdUs+huoy2OZmmgPjI3shl7fMt+3ZAIRWVI3WNBIDDJasetGTR6aWf2YGfgI6HAixNCkacP3pD0utGcmu5RWGGN+IreBZtRFQS5hYern1ILq8jCpVKt+QOdVNE4D+lXGpIlXY4kgul3YuU+D6mD+1N/8i7KmgT50rTB/Sr9Cfn85j5xqwh5VHcdf8v9z6VVs8ulczYy/KKV6ZMJUQAcraRNvwQsLl7MqchX3yzF8Q0LvtQCqcqKyXK0aoSl4drFdNzf0rQ/N5vR14UIP6A/aCIP09gpsxeumC8RWjLDtACTLGodU5JhqBCgmYNhfVO17+EzXbvjuhf0uB31f7zI25mGiHSqdRfoG+/yZ/eNpuBhCJ0Nu/LvvBxUco8GfHH7fA12EnEQ25JDUdXNTSUhL78UE/jmxMNv1if87OGLxQG5vPxv0JelgPBfxwTURQn0aBPETl7lm/IGBhsNZCr8KJoPqNaN1FjeqIAmgBk0I3v9/V67rVZJARO0Nn5Wwn6DD4d7vEIEyHu/tGHaioObNEGX5ul4s+j23nY3iXhM75TISzUFpPx/5FyH/xclec+k6lFHA=
  - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
  - PROJECT_NAME_STG=stage-cd
  - CLUSTER_NAME_STG=cd-test
    #- PROJECT_NAME_PRD=<YOUR_PROJECT_NAME>
  #- CLUSTER_NAME_PRD=<YOUR_CLUSTER_NAME>
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a	
  - DOCKER_IMAGE_NAME=openebs
  - KUBE_DEPLOYMENT_NAME=openebs
  - KUBE_DEPLOYMENT_CONTAINER_NAME=openebs
  - NODE_ENV=CI
  - COMMIT=${TRAVIS_COMMIT::6}
# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
install:
  - npm install

script:
  - npm test

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  email:
    on_success: never
on_failure: always

